apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault-operator
  chart:
    repository: https://kubernetes-charts.banzaicloud.com
    name: vault-operator
    version: 0.9.0
  values:
    args:
      - --set=etcd-operator.enabled=true
      - --set=etcd-operator.etcdOperator.commandArgs.cluster-wide=true
