

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
spec:
  releaseName: vault-operator
  chart:
    spec:
      chart: vault-operator
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
      version: "0.9.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
  values:
    args:
      - --set=etcd-operator.enabled=true
      - --set=etcd-operator.etcdOperator.commandArgs.cluster-wide=true
